version: "3.9"

networks:
  cealgull_peers:
    name: "cealgull"

services:
  cealgullp1:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=p1.cealgull.com
      - CORE_PEER_ADDRESS=p1.cealgull.com:7051
      - CORE_PEER_LOCALMSPID=cealgullMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/cealgullp1/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cealgullPeers
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/cealgullp1/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/cealgullp1/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/cealgullp1/tls/tlscacerts/tls-0-0-0-0-7054.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p1.cealgull.com:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    hostname: "p1.cealgull.com"
    volumes:
      - /var/run:/host/var/run
      - ./cealgullp1:/etc/hyperledger/cealgullp1

    networks:
      - cealgull_peers

  cealgullp2:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=p2.cealgull.com
      - CORE_PEER_ADDRESS=p2.cealgull.com:7051
      - CORE_PEER_LOCALMSPID=cealgullMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/cealgullp2/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cealgullPeers
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/cealgullp2/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/cealgullp2/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/cealgullp2/tls/tlscacerts/tls-0-0-0-0-7054.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p2.cealgull.com:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=p1.cealgull.com:7051
    hostname: "p2.cealgull.com"
    volumes:
      - /var/run:/host/var/run
      - ./cealgullp2:/etc/hyperledger/cealgullp2
    networks:
      - cealgull_peers
  cli:
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=p1.cealgull.com:7051
      - CORE_PEER_LOCALMSPID=cealgullMSP
      - CORE_PEER_TLS_ENABLED=true
    command: sh
    volumes:
      - ./cealgullo1/orderer:/etc/hyperledger/orderer
      - ./cealgullp1:/etc/hyperledger/cealgullp1
      - ./cealgullp2:/etc/hyperledger/cealgullp2
      - ./admin:/etc/hyperledger/admin
    networks:
      - cealgull_peers
